config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  resources :contract, only: :index
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contract_controller.rb
# frozen_string_literal: true

class ContractController < ApplicationController
  def index; end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/contract/index.html.slim
.col-md-7
  textarea.form-control#source rows=30
.col-md-5
  .row
    select#versions.form-control
  .row
    .alert.alert-warning.hidden#status
  .row
    button#compile-btn.btn.btn-info.btn-xl disabled="" Compile
  .row
    .panel-group#compiled-contracts aria-multiselectable="true" role="tablist"

app/views/home/index.html.slim
.jumbotron
  .container
    h1.display-3 Hello!
    p This service will allow you to compile and deploy a smart contract into the Rinkeby Ethereum test network
    p= link_to 'Compile & Deploy »', contract_index_path, class: 'btn btn-primary btn-lg'

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "SolidityDeployer"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"
  body
    .navbar.navbar-default.navbar-static-top
        .container
          button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href="#"SolidityDeployer
    .container
      .row
        .col-lg-12
          = bootstrap_flash
          = yield

      footer.footer
        p &copy; Aleksandr 2018
    = javascript_include_tag 'application'
    = javascript_include_tag 'browser-solc.min.js'
    script src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/4.4.0/bootbox.min.js"